version: '3.8'

services:
  forex-choch-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forex-choch-detector
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    networks:
      - forex-network
    restart: unless-stopped
    command: python -m src.cli.main run --config /app/config.yaml

  redis:
    image: redis:7-alpine
    container_name: forex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - forex-network
    restart: unless-stopped

  webhook-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forex-webhook
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - forex-network
    restart: unless-stopped
    command: uvicorn src.region.webhook_handler:app --host 0.0.0.0 --port 8000

networks:
  forex-network:
    driver: bridge

volumes:
  redis_data:
